### ISSUE TITLE
Issue Cuda out of memory

### ISSUE THREAD

**Issue by Axienne** [JarodMica/ai-voice-cloning#122]
Hi. I have this issue. Does anyone have an answer?   
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacity of 4.00 GiB of which 0 bytes is free. Of the allocated memory 3.41 GiB is allocated by PyTorch, and 53.04 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by maepopi** [comment]
Hey,
Strange that it happens right from the start. Have you tried clearing the torch GPU cache? It does the trick for me sometimes.
In your console, type "python" while in the virtual environment, then do
`
import torch
torch.cuda.empty_cache()
exit()
`

Not sure it will help but there's no harm in trying I guess!
